global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'paca-api'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['paca-api:9090']
    scrape_timeout: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093